### ISSUE TITLE
Make mobs mobile.

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#175]
Right now, the only moving NPC is the puppy that can follow you.

It would be nice to see two other types of mobiles that could be done with relative ease without having to get into A* or have coordinate-based rooms:

1. Random movement. After a wait time, the mob picks an exit at random and moves through it. Repeat.
2. Patrolling. The mob moves back and forth along a predetermined route.

These would be configurable behaviors, for example:

An NPC that moves into a random exit every 10 seconds.
```
behaviors:
    randommove:
        wait: 10
```

An NPC that patrols east twice, then back to the start, moving every 16 seconds.
```
behaviors:
    patrol:
        wait: 16
        loop: true
        route: [ "e", "e" ]
```
