### ISSUE TITLE
Behavior for rooms to have custom commands

### ISSUE THREAD

**Issue by shawncplus** [shawncplus/ranviermud#196]
Create a `custom-commands` behavior with a config similar to the following

```yaml
script: "my-room-script"
behaviors:
  custom-commands:
    - push
    - pull
```

When the commands input event fails to find a valid command or skill to execute it will check to see if the room the player is in has this behavior and if so check that the command entered is in the whitelist of commands. If both of those are true then it should fire an event on the room the same name as the command entered.

This will allow functionality of rooms having custom commands for the purposes of quests or other things.
